### PR TITLE
[AUTOMATED TEST] The instructions page shows up after clicking the in…

### PR DESCRIPTION
**Pull request by grandmaJ**
…structions button on the game page

#7 
#28 
#40

### CODE REVIEW

**Review by LutfiyaCharfaray — APPROVED** [review]
Tests are well executed! Tests exist to check and verify that the instructions page button takes you to the page when pressed; and that the expected heading is present.

**Comment by Kavishar29** [comment]
## Critic:
- when running the master branch a bug was found and the test did not pass.

##Resolve:
- please resolve the issue such that the deployment passes @grandmaJ

**Comment by grandmaJ** [comment]
## Response:
- Have been trying to fix the bug and will continue to work on the deployment.
- It successfully runs on local machine but does not build on Github, trying to figure it out.
- Thanks for the feedback!

**Comment by grandmaJ** [comment]
> ## Critic:
> * when running the master branch a bug was found and the test did not pass.
> 
> ## Resolve:
> * please resolve the issue such that the deployment passes @grandmaJ

Thanks for the feedback Lutfiya and Kavisha! I have successfully resolved the build and deployment issue by using Playwright and Jest instead of Selenium and Jest. Never knew what a difference it would make!

**Pull request merged**
